[[redirects]]
  from = "/buy1"
  to = "https://shopanov.com/fume/sendleads.php"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"
